config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification' }
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  resources :tutorials
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, 
         :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tutorial.rb
class Tutorial < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
	before_action :authenticate_admin!, only: [:create, :new, :edit, :update, :destroy]
	skip_before_action :verify_authenticity_token

	def create
		@tutorial = Tutorial.new(tutorial_params)

		if @tutorial.save
			redirect_to @tutorial
		else
			render 'new'
		end
	end

	def new
		@tutorial = Tutorial.new
	end

	def edit
        @tutorial = Tutorial.find(params[:id])
	end

	def show
		@tutorial = Tutorial.find(params[:id])
	end

	def update
	    @tutorial = Tutorial.find(params[:id])
 
		if @tutorial.update(tutorial_params)
		  redirect_to @tutorial
		else
		  render 'edit'
        end
	end

	def destroy
		@tutorial = Tutorial.find(params[:id])
		@tutorial.destroy

		redirect_to tutorials_path
	end

	private
		def tutorial_params
			params.require(:tutorial).permit(:title, :explanation, :code, :interactive)
		end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechTeamProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tutorials/_form.html.erb
<%= form_with(model: @tutorial, local: true) do |form| %>
 
  <% if @tutorial.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@tutorial.errors.count, "error") %> prohibited
        this tutorial from being saved:
      </h2>
      <ul>
        <% @tutorial.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :explanation %><br>
    <%= form.text_area :explanation %>
  </p>

  <p>
    <%= form.label :code %><br>
    <%= form.text_area :code %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/tutorials/edit.html.erb
<h1>Edit tutorial</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', tutorials_path %>

app/views/tutorials/index.html.erb
<h1>Listing Tutorials</h1>
<%= link_to 'New tutorial', new_tutorial_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
  
  <% if @tutorials %>
    <% @tutorials.each do |tutorial| %>
      <tr>
        <td><%= tutorial.title %></td>
        <td><%= tutorial.text %></td>
        <td><%= link_to 'Show', tutorial_path(tutorial) %></td>
        <td><%= link_to 'Edit', edit_tutorial_path(tutorial) %></td>
        <td><%= link_to 'Destroy', tutorial_path(tutorial),
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  <% else %>
    <tr>
      <td>No tutorials</td>
    </tr>
  <% end %>

app/views/tutorials/new.html.erb
<h1>New Tutorial</h1>

<%= render 'form' %>

<%= link_to 'Back', tutorials_path %>

app/views/tutorials/show.html.erb
<!DOCTYPE html>

<html>
  <head>
  	<title>Hello</title>
    <%= stylesheet_link_tag "tutorials" %>
    <link href="https://fonts.googleapis.com/css?family=Anonymous+Pro" rel="stylesheet"> 
  </head>
  <body>
    <div id="top">
      <%= link_to "<-", tutorial_path(@tutorial.id - 1), class: "arrowWrapper", id: "leftArrow" %>
      <%= link_to "->", tutorial_path(@tutorial.id + 1), class: "arrowWrapper", id: "rightArrow" %>
    	<h1 id="title">
    		<%= @tutorial.title %>
    	</h1>
      <div id="run" onclick="runCode()">
        Run code
      </div>
      <div id="spacer"></div>
    </div>

    <div id="main">
      <div id="left">
      	<p id="explanation">
      		<%= @tutorial.explanation.html_safe %>
        </p>
      </div>
        <textarea id="code"
        placeholder="Type your code here"><%= @tutorial.code %></textarea>
      </div>
    </div>

    <div id="output">
      <div id="caret">
        >
      </div>
      <div id="outputText"></div>
    </div>

  </body>
 </html>

app/views/welcome/index.html.erb
<!DOCTYPE html>

<html>
  <head>
    <meta charset="UTF-8">
    <title>WOW! PROGRAMMING!</title>
    <%= stylesheet_link_tag "welcome" %>
  </head>
  
  <body onclick="changeWelcomeText()">
  	<h1 id="welcome">Welcome to a programming tutorial!</h1>
  </body>
</html>